export interface ThemeFonts {
    headingFont: string;
    bodyFont: string;
}

export interface PredefinedTheme {
    id: string;
    name: string;
    category: 'business' | 'marketing' | 'educational';
    colors: string[];
    textColor: string;
    fonts: ThemeFonts;
    titleBarBg: string;
    titleBarText: string;
    canvasBg: string;
    phaseTextColor?: string;
    cardTitleColor?: string;
    cardContentColor?: string;
    cardSubtextColor?: string;
}

// Business & Corporate Presentations
const businessThemes: PredefinedTheme[] = [
    {
        id: 'executive-boardroom',
        name: 'Executive Boardroom',
        category: 'business',
        colors: ['#0A192F', '#112240', '#233554', '#495670', '#8892B0', '#CCD6F6', '#E6F1FF'],
        textColor: '#F8FAFC',
        fonts: { headingFont: `'Inter', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#0A192F',
        titleBarText: '#F8FAFC',
        canvasBg: '#112240',
        phaseTextColor: '#E6F1FF',
        cardTitleColor: '#F8FAFC',
        cardContentColor: '#CCD6F6',
        cardSubtextColor: '#8892B0',
    },
    {
        id: 'trust-finance',
        name: 'Trust & Finance',
        category: 'business',
        colors: ['#002D62', '#0066CC', '#4C9EEB', '#B3D4F5', '#E5F0FA', '#FFC000'],
        textColor: '#111827',
        fonts: { headingFont: `'Montserrat', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#002D62',
        titleBarText: '#FFFFFF',
        canvasBg: '#F0F7FF',
        phaseTextColor: '#111827',
        cardTitleColor: '#002D62',
        cardContentColor: '#1A1A1A',
        cardSubtextColor: '#4D4D4D',
    },
    {
        id: 'modern-minimalist',
        name: 'Modern Minimalist',
        category: 'business',
        colors: ['#18181B', '#27272A', '#3F3F46', '#52525B', '#A1A1AA', '#D4D4D8', '#F4F4F5'],
        textColor: '#FAFAFA',
        fonts: { headingFont: `'Space Grotesk', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#18181B',
        titleBarText: '#FAFAFA',
        canvasBg: '#27272A',
        phaseTextColor: '#FAFAFA',
        cardTitleColor: '#FAFAFA',
        cardContentColor: '#D4D4D8',
        cardSubtextColor: '#A1A1AA',
    },
    {
        id: 'industrial-chic',
        name: 'Industrial Chic',
        category: 'business',
        colors: ['#212529', '#343A40', '#495057', '#6C757D', '#ADB5BD', '#DEE2E6', '#F8F9FA'],
        textColor: '#FFFFFF',
        fonts: { headingFont: `'Roboto', sans-serif`, bodyFont: `'Roboto', sans-serif` },
        titleBarBg: '#212529',
        titleBarText: '#F8F9FA',
        canvasBg: '#F8F9FA',
        phaseTextColor: '#212529',
        cardTitleColor: '#212529',
        cardContentColor: '#495057',
        cardSubtextColor: '#6C757D',
    },
    {
        id: 'global-tech',
        name: 'Global Tech',
        category: 'business',
        colors: ['#0F172A', '#1E293B', '#334155', '#475569', '#94A3B8', '#CBD5E1', '#F1F5F9'],
        textColor: '#0F172A',
        fonts: { headingFont: `'Outfit', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#0F172A',
        titleBarText: '#F1F5F9',
        canvasBg: '#F8FAFC',
        phaseTextColor: '#0F172A',
        cardTitleColor: '#0F172A',
        cardContentColor: '#334155',
        cardSubtextColor: '#64748B',
    },
    {
        id: 'classic-consulting',
        name: 'Classic Consulting',
        category: 'business',
        colors: ['#1C2833', '#2E4053', '#566573', '#808B96', '#ABB2B9', '#D5D8DC', '#EAECEE'],
        textColor: '#17202A',
        fonts: { headingFont: `'Merriweather', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#1C2833',
        titleBarText: '#EAECEE',
        canvasBg: '#F5F6F7',
        phaseTextColor: '#17202A',
        cardTitleColor: '#1C2833',
        cardContentColor: '#2E4053',
        cardSubtextColor: '#566573',
    },
    {
        id: 'green-energy',
        name: 'Green Energy',
        category: 'business',
        colors: ['#004B23', '#006400', '#007200', '#008000', '#38B000', '#70E000', '#9EF01A'],
        textColor: '#00120B',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#004B23',
        titleBarText: '#FFFFFF',
        canvasBg: '#F0FFF0',
        phaseTextColor: '#004B23',
        cardTitleColor: '#006400',
        cardContentColor: '#00120B',
        cardSubtextColor: '#38B000',
    },
    {
        id: 'urban-architecture',
        name: 'Urban Architecture',
        category: 'business',
        colors: ['#2B2D42', '#8D99AE', '#EDF2F4', '#EF233C', '#D90429', '#4A4E69', '#9A8C98'],
        textColor: '#2B2D42',
        fonts: { headingFont: `'Playfair Display', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#2B2D42',
        titleBarText: '#EDF2F4',
        canvasBg: '#EDF2F4',
        phaseTextColor: '#2B2D42',
        cardTitleColor: '#2B2D42',
        cardContentColor: '#4A4E69',
        cardSubtextColor: '#8D99AE',
    },
    {
        id: 'premium-luxury',
        name: 'Premium Luxury',
        category: 'business',
        colors: ['#000000', '#14213D', '#FCA311', '#E5E5E5', '#FFFFFF', '#D4AF37', '#8B7355'],
        textColor: '#FCA311',
        fonts: { headingFont: `'Playfair Display', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#000000',
        titleBarText: '#FCA311',
        canvasBg: '#14213D',
        phaseTextColor: '#FCA311',
        cardTitleColor: '#FCA311',
        cardContentColor: '#E5E5E5',
        cardSubtextColor: '#D4AF37',
    },
    {
        id: 'corporate-monochrome',
        name: 'Corporate Monochrome',
        category: 'business',
        colors: ['#121212', '#282828', '#3F3F3F', '#575757', '#717171', '#8D8D8D', '#AAAAAA'],
        textColor: '#E0E0E0',
        fonts: { headingFont: `'Space Grotesk', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#121212',
        titleBarText: '#E0E0E0',
        canvasBg: '#1A1A1A',
        phaseTextColor: '#E0E0E0',
        cardTitleColor: '#E0E0E0',
        cardContentColor: '#AAAAAA',
        cardSubtextColor: '#8D8D8D',
    },
];

// Marketing & High-Conversion Presentations
const marketingThemes: PredefinedTheme[] = [
    {
        id: 'vibrant-startup',
        name: 'Vibrant Startup',
        category: 'marketing',
        colors: ['#4A00E0', '#8E2DE2', '#FF0099', '#493240', '#F5F5F5', '#E0E0E0', '#BDBDBD'],
        textColor: '#212121',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#4A00E0',
        titleBarText: '#FFFFFF',
        canvasBg: '#F5F5F5',
        phaseTextColor: '#212121',
        cardTitleColor: '#4A00E0',
        cardContentColor: '#493240',
        cardSubtextColor: '#8E2DE2',
    },
    {
        id: 'sunset-conversion',
        name: 'Sunset Conversion',
        category: 'marketing',
        colors: ['#FF512F', '#DD2476', '#FF9A44', '#FC6076', '#FF9A9E', '#FECFEF', '#FFF1EB'],
        textColor: '#1E1E1E',
        fonts: { headingFont: `'Montserrat', sans-serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#FF512F',
        titleBarText: '#FFFFFF',
        canvasBg: '#FFF1EB',
        phaseTextColor: '#1E1E1E',
        cardTitleColor: '#DD2476',
        cardContentColor: '#1E1E1E',
        cardSubtextColor: '#FF512F',
    },
    {
        id: 'neon-cyberpunk',
        name: 'Neon Cyberpunk',
        category: 'marketing',
        colors: ['#0B0C10', '#1F2833', '#C5C6C7', '#66FCF1', '#45A29E', '#FF007F', '#7D12FF'],
        textColor: '#C5C6C7',
        fonts: { headingFont: `'Space Grotesk', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#0B0C10',
        titleBarText: '#66FCF1',
        canvasBg: '#1F2833',
        phaseTextColor: '#C5C6C7',
        cardTitleColor: '#66FCF1',
        cardContentColor: '#C5C6C7',
        cardSubtextColor: '#45A29E',
    },
    {
        id: 'bold-punchy',
        name: 'Bold & Punchy',
        category: 'marketing',
        colors: ['#D90429', '#EF233C', '#EDF2F4', '#8D99AE', '#2B2D42', '#FFB703', '#FB8500'],
        textColor: '#EDF2F4',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Roboto', sans-serif` },
        titleBarBg: '#D90429',
        titleBarText: '#EDF2F4',
        canvasBg: '#F8F9FA',
        phaseTextColor: '#2B2D42',
        cardTitleColor: '#D90429',
        cardContentColor: '#2B2D42',
        cardSubtextColor: '#8D99AE',
    },
    {
        id: 'earthy-wellness',
        name: 'Earthy Wellness',
        category: 'marketing',
        colors: ['#283618', '#606C38', '#DDA15E', '#BC6C25', '#FEFAE0', '#FAEDCD', '#E9EDC9'],
        textColor: '#283618',
        fonts: { headingFont: `'Merriweather', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#283618',
        titleBarText: '#FEFAE0',
        canvasBg: '#FEFAE0',
        phaseTextColor: '#283618',
        cardTitleColor: '#606C38',
        cardContentColor: '#283618',
        cardSubtextColor: '#BC6C25',
    },
    {
        id: 'playful-pop',
        name: 'Playful Pop',
        category: 'marketing',
        colors: ['#FFD166', '#06D6A0', '#118AB2', '#EF476F', '#073B4C', '#F8F9FA', '#E9ECEF'],
        textColor: '#073B4C',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#073B4C',
        titleBarText: '#F8F9FA',
        canvasBg: '#F8F9FA',
        phaseTextColor: '#073B4C',
        cardTitleColor: '#118AB2',
        cardContentColor: '#073B4C',
        cardSubtextColor: '#06D6A0',
    },
    {
        id: 'ocean-wave-b2c',
        name: 'Ocean Wave B2C',
        category: 'marketing',
        colors: ['#03045E', '#023E8A', '#0077B6', '#0096C7', '#00B4D8', '#48CAE4', '#90E0EF'],
        textColor: '#03045E',
        fonts: { headingFont: `'Montserrat', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#03045E',
        titleBarText: '#CAF0F8',
        canvasBg: '#F0F9FF',
        phaseTextColor: '#03045E',
        cardTitleColor: '#0077B6',
        cardContentColor: '#023E8A',
        cardSubtextColor: '#0096C7',
    },
    {
        id: 'elegant-rose-gold',
        name: 'Elegant Rose Gold',
        category: 'marketing',
        colors: ['#B68D40', '#D6AD60', '#F4EBD0', '#122620', '#D6BC97', '#E8D8C4', '#FFFFFF'],
        textColor: '#122620',
        fonts: { headingFont: `'Playfair Display', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#122620',
        titleBarText: '#F4EBD0',
        canvasBg: '#F4EBD0',
        phaseTextColor: '#122620',
        cardTitleColor: '#B68D40',
        cardContentColor: '#122620',
        cardSubtextColor: '#D6AD60',
    },
    {
        id: 'dynamic-citrus',
        name: 'Dynamic Citrus',
        category: 'marketing',
        colors: ['#FF7B00', '#FF8800', '#FF9500', '#FFA200', '#FFAA00', '#FFB700', '#FFC300'],
        textColor: '#000814',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#FF7B00',
        titleBarText: '#000814',
        canvasBg: '#FFF8E7',
        phaseTextColor: '#000814',
        cardTitleColor: '#FF7B00',
        cardContentColor: '#000814',
        cardSubtextColor: '#FF9500',
    },
    {
        id: 'the-disruptor',
        name: 'The Disruptor',
        category: 'marketing',
        colors: ['#7400B8', '#6930C3', '#5E60CE', '#5390D9', '#4EA8DE', '#48BFE3', '#56CFE1'],
        textColor: '#FFFFFF',
        fonts: { headingFont: `'Outfit', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#7400B8',
        titleBarText: '#FFFFFF',
        canvasBg: '#F3E8FF',
        phaseTextColor: '#7400B8',
        cardTitleColor: '#7400B8',
        cardContentColor: '#6930C3',
        cardSubtextColor: '#5390D9',
    },
];

// Educational & Academic Presentations
const educationalThemes: PredefinedTheme[] = [
    {
        id: 'classic-chalkboard',
        name: 'Classic Chalkboard',
        category: 'educational',
        colors: ['#2F4F4F', '#1E3F20', '#4A7C59', '#8FC0A9', '#C8D5B9', '#FAF3DD', '#F1E3D3'],
        textColor: '#FAF3DD',
        fonts: { headingFont: `'Merriweather', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#2F4F4F',
        titleBarText: '#FAF3DD',
        canvasBg: '#1E3F20',
        phaseTextColor: '#FAF3DD',
        cardTitleColor: '#FAF3DD',
        cardContentColor: '#C8D5B9',
        cardSubtextColor: '#8FC0A9',
    },
    {
        id: 'scholarly-library',
        name: 'Scholarly Library',
        category: 'educational',
        colors: ['#3C2F2F', '#4B3832', '#854442', '#FFF4E6', '#E4D5B7', '#D9B08C', '#116466'],
        textColor: '#3C2F2F',
        fonts: { headingFont: `'Playfair Display', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#3C2F2F',
        titleBarText: '#FFF4E6',
        canvasBg: '#FFF4E6',
        phaseTextColor: '#3C2F2F',
        cardTitleColor: '#854442',
        cardContentColor: '#3C2F2F',
        cardSubtextColor: '#116466',
    },
    {
        id: 'clear-cognition',
        name: 'Clear Cognition',
        category: 'educational',
        colors: ['#EBF4FA', '#D1E8E2', '#1978A5', '#034F84', '#F7CAC9', '#92A8D1', '#3E4C59'],
        textColor: '#034F84',
        fonts: { headingFont: `'Inter', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#034F84',
        titleBarText: '#EBF4FA',
        canvasBg: '#EBF4FA',
        phaseTextColor: '#034F84',
        cardTitleColor: '#1978A5',
        cardContentColor: '#034F84',
        cardSubtextColor: '#3E4C59',
    },
    {
        id: 'muted-earth-dyslexia',
        name: 'Muted Earth (Dyslexia Friendly)',
        category: 'educational',
        colors: ['#FFF8E7', '#EADDD7', '#D5C7BC', '#988780', '#524641', '#382E2B', '#5B7B7A'],
        textColor: '#382E2B',
        fonts: { headingFont: `'Open Sans', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#382E2B',
        titleBarText: '#FFF8E7',
        canvasBg: '#FFF8E7',
        phaseTextColor: '#382E2B',
        cardTitleColor: '#524641',
        cardContentColor: '#382E2B',
        cardSubtextColor: '#5B7B7A',
    },
    {
        id: 'scientific-method',
        name: 'Scientific Method',
        category: 'educational',
        colors: ['#0B3C5D', '#328CC1', '#D9B310', '#1D2731', '#F8F8F8', '#E2E2E2', '#B0BEC5'],
        textColor: '#1D2731',
        fonts: { headingFont: `'Roboto', sans-serif`, bodyFont: `'Roboto', sans-serif` },
        titleBarBg: '#0B3C5D',
        titleBarText: '#F8F8F8',
        canvasBg: '#F8F8F8',
        phaseTextColor: '#1D2731',
        cardTitleColor: '#0B3C5D',
        cardContentColor: '#1D2731',
        cardSubtextColor: '#328CC1',
    },
    {
        id: 'primary-colors-refined',
        name: 'Primary Colors Refined',
        category: 'educational',
        colors: ['#C1272D', '#F7931E', '#FCEE21', '#39B54A', '#00AEEF', '#2B3990', '#F2F2F2'],
        textColor: '#333333',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#2B3990',
        titleBarText: '#F2F2F2',
        canvasBg: '#F8F8F8',
        phaseTextColor: '#333333',
        cardTitleColor: '#2B3990',
        cardContentColor: '#333333',
        cardSubtextColor: '#555555',
    },
    {
        id: 'calm-focus',
        name: 'Calm Focus',
        category: 'educational',
        colors: ['#EDF5E1', '#C5D5CB', '#9FA9A3', '#E3E0CF', '#5CDB95', '#379683', '#05386B'],
        textColor: '#05386B',
        fonts: { headingFont: `'Montserrat', sans-serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#05386B',
        titleBarText: '#EDF5E1',
        canvasBg: '#EDF5E1',
        phaseTextColor: '#05386B',
        cardTitleColor: '#379683',
        cardContentColor: '#05386B',
        cardSubtextColor: '#5CDB95',
    },
    {
        id: 'creative-arts',
        name: 'Creative Arts',
        category: 'educational',
        colors: ['#F94144', '#F3722C', '#F8961E', '#F9C74F', '#90BE6D', '#43AA8B', '#577590'],
        textColor: '#FFFFFF',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#F94144',
        titleBarText: '#FFFFFF',
        canvasBg: '#FFF5F5',
        phaseTextColor: '#577590',
        cardTitleColor: '#F94144',
        cardContentColor: '#577590',
        cardSubtextColor: '#F8961E',
    },
    {
        id: 'warm-history',
        name: 'Warm History',
        category: 'educational',
        colors: ['#582F0E', '#7F4F24', '#936639', '#A68A64', '#B6AD90', '#C2C5AA', '#A4AC86'],
        textColor: '#582F0E',
        fonts: { headingFont: `'Merriweather', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#582F0E',
        titleBarText: '#C2C5AA',
        canvasBg: '#F5F3EE',
        phaseTextColor: '#582F0E',
        cardTitleColor: '#7F4F24',
        cardContentColor: '#582F0E',
        cardSubtextColor: '#936639',
    },
    {
        id: 'future-innovators',
        name: 'Future Innovators',
        category: 'educational',
        colors: ['#264653', '#2A9D8F', '#E9C46A', '#F4A261', '#E76F51', '#F2E8CF', '#A8DADC'],
        textColor: '#264653',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#264653',
        titleBarText: '#F2E8CF',
        canvasBg: '#F2E8CF',
        phaseTextColor: '#264653',
        cardTitleColor: '#2A9D8F',
        cardContentColor: '#264653',
        cardSubtextColor: '#E76F51',
    },
];

// Legacy themes for backward compatibility
const legacyThemes: PredefinedTheme[] = [
    {
        id: 'ocean-depth',
        name: 'Ocean Depth',
        category: 'business',
        colors: ['#e0f2fe', '#bae6fd', '#7dd3fc', '#38bdf8', '#0ea5e9', '#0284c7'],
        textColor: '#0f172a',
        fonts: { headingFont: `'Inter', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#0c4a6e',
        titleBarText: '#ffffff',
        canvasBg: '#f0f9ff',
        phaseTextColor: '#0f172a',
        cardTitleColor: '#0f172a',
        cardContentColor: '#334155',
        cardSubtextColor: '#64748b',
    },
    {
        id: 'sunset-glow',
        name: 'Sunset Glow',
        category: 'marketing',
        colors: ['#fef08a', '#fbbf24', '#f59e0b', '#ea580c', '#e11d48', '#be123c'],
        textColor: '#450a0a',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#7f1d1d',
        titleBarText: '#fef2f2',
        canvasBg: '#fffbeb',
        phaseTextColor: '#450a0a',
        cardTitleColor: '#450a0a',
        cardContentColor: '#7c2d12',
        cardSubtextColor: '#c2410c',
    },
    {
        id: 'forest-canopy',
        name: 'Forest Canopy',
        category: 'business',
        colors: ['#dcfce7', '#bbf7d0', '#86efac', '#4ade80', '#22c55e', '#16a34a'],
        textColor: '#064e3b',
        fonts: { headingFont: `'Merriweather', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#14532d',
        titleBarText: '#f0fdf4',
        canvasBg: '#f0fdf4',
        phaseTextColor: '#064e3b',
        cardTitleColor: '#064e3b',
        cardContentColor: '#166534',
        cardSubtextColor: '#15803d',
    },
    {
        id: 'corporate-clean',
        name: 'Corporate Clean',
        category: 'business',
        colors: ['#6929c4', '#1192e8', '#005d5d', '#9f1853', '#198038', '#ba4e00'],
        textColor: '#ffffff',
        fonts: { headingFont: `'Montserrat', sans-serif`, bodyFont: `'Roboto', sans-serif` },
        titleBarBg: '#161616',
        titleBarText: '#ffffff',
        canvasBg: '#f4f4f4',
        phaseTextColor: '#161616',
        cardTitleColor: '#161616',
        cardContentColor: '#333333',
        cardSubtextColor: '#666666',
    },
    {
        id: 'monochrome-slate',
        name: 'Monochrome Slate',
        category: 'business',
        colors: ['#f1f5f9', '#e2e8f0', '#cbd5e1', '#94a3b8', '#64748b', '#475569'],
        textColor: '#0f172a',
        fonts: { headingFont: `'Space Grotesk', sans-serif`, bodyFont: `'Inter', sans-serif` },
        titleBarBg: '#1e293b',
        titleBarText: '#f1f5f9',
        canvasBg: '#f8fafc',
        phaseTextColor: '#0f172a',
        cardTitleColor: '#0f172a',
        cardContentColor: '#334155',
        cardSubtextColor: '#64748b',
    },
    {
        id: 'midnight-neon',
        name: 'Midnight Neon',
        category: 'marketing',
        colors: ['#312e81', '#4338ca', '#6366f1', '#818cf8', '#a5b4fc', '#c7d2fe'],
        textColor: '#ffffff',
        fonts: { headingFont: `'Outfit', sans-serif`, bodyFont: `'Space Grotesk', sans-serif` },
        titleBarBg: '#0f0a2e',
        titleBarText: '#e0e7ff',
        canvasBg: '#1e1b4b',
        phaseTextColor: '#e0e7ff',
        cardTitleColor: '#c7d2fe',
        cardContentColor: '#a5b4fc',
        cardSubtextColor: '#818cf8',
    },
    {
        id: 'warm-earth',
        name: 'Warm Earth',
        category: 'educational',
        colors: ['#fef3c7', '#fde68a', '#fcd34d', '#f59e0b', '#d97706', '#b45309'],
        textColor: '#451a03',
        fonts: { headingFont: `'Playfair Display', serif`, bodyFont: `'Lato', sans-serif` },
        titleBarBg: '#451a03',
        titleBarText: '#fef3c7',
        canvasBg: '#fffbeb',
        phaseTextColor: '#451a03',
        cardTitleColor: '#78350f',
        cardContentColor: '#92400e',
        cardSubtextColor: '#b45309',
    },
    {
        id: 'berry-blast',
        name: 'Berry Blast',
        category: 'marketing',
        colors: ['#fce7f3', '#fbcfe8', '#f9a8d4', '#f472b6', '#ec4899', '#db2777'],
        textColor: '#500724',
        fonts: { headingFont: `'Poppins', sans-serif`, bodyFont: `'Open Sans', sans-serif` },
        titleBarBg: '#831843',
        titleBarText: '#fdf2f8',
        canvasBg: '#fdf2f8',
        phaseTextColor: '#500724',
        cardTitleColor: '#831843',
        cardContentColor: '#9d174d',
        cardSubtextColor: '#db2777',
    },
];

export const PREDEFINED_THEMES: PredefinedTheme[] = [
    ...businessThemes,
    ...marketingThemes,
    ...educationalThemes,
    ...legacyThemes,
];

export const THEMES_BY_CATEGORY = {
    business: businessThemes,
    marketing: marketingThemes,
    educational: educationalThemes,
    legacy: legacyThemes,
};

export const THEME_CATEGORIES: { id: 'business' | 'marketing' | 'educational' | 'legacy'; label: string }[] = [
    { id: 'business', label: 'Business & Corporate' },
    { id: 'marketing', label: 'Marketing & Conversion' },
    { id: 'educational', label: 'Educational & Academic' },
    { id: 'legacy', label: 'Classic Themes' },
];
